import { Language, TranslationSet } from './types';

type Translations = {
  [key in Language]: TranslationSet;
};

export const TRANSLATIONS: Translations = {
  [Language.EN]: {
    app_title: "AI Career Match",
    app_subtitle: "Uncover your ideal career path. Describe your skills, experience, and professional aspirations below, and let our AI illuminate the possibilities.",
    profile_placeholder: "e.g., '5 years of experience in React and Node.js, passionate about building scalable web applications. Looking for a senior role in a fast-paced startup...'",
    location_placeholder: "e.g., India",
    analyze_button: "Find My Match",
    analyzing: "Finding matches...",
    error_title: "Error:",
    error_empty: "Please describe your profile and provide a location.",
    error_generic: "An unexpected error occurred. Please try again.",
    loader_text: "Our AI is searching for your ideal career matches...",
    match_results_title: "Career Opportunities For You",
    summary_title: "Why it's a match",
  },
  [Language.TA]: {
    app_title: "AI தொழில் பொருத்தம்",
    app_subtitle: "உங்கள் சிறந்த தொழில் பாதையைக் கண்டறியுங்கள். உங்கள் திறமைகள், அனுபவம் மற்றும் தொழில்முறை லட்சியங்களை கீழே விவரிக்கவும், எங்கள் AI சாத்தியங்களை ஒளிரச் செய்யட்டும்.",
    profile_placeholder: "எ.கா., 'ரியாக்ட் மற்றும் நோட்.ஜேஎஸ்-ல் 5 வருட அனுபவம், அளவிடக்கூடிய வலை பயன்பாடுகளை உருவாக்குவதில் ஆர்வம். ஒரு வேகமான ஸ்டார்ட்அப்பில் ஒரு மூத்த பாத்திரத்தைத் தேடுகிறேன்...'",
    location_placeholder: "எ.கா., இந்தியா",
    analyze_button: "என் பொருத்தத்தைக் கண்டுபிடி",
    analyzing: "பொருத்தங்களைக் கண்டறிகிறது...",
    error_title: "பிழை:",
    error_empty: "உங்கள் சுயவிவரத்தை விவரித்து ஒரு இருப்பிடத்தை வழங்கவும்.",
    error_generic: "எதிர்பாராத பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    loader_text: "எங்கள் AI உங்கள் சிறந்த தொழில் பொருத்தங்களைத் தேடுகிறது...",
    match_results_title: "உங்களுக்கான தொழில் வாய்ப்புகள்",
    summary_title: "ஏன் இது ஒரு பொருத்தம்",
  },
  [Language.TE]: {
    app_title: "AI కెరీర్ మ్యాచ్",
    app_subtitle: "మీ ఆదర్శ కెరీర్ మార్గాన్ని కనుగొనండి. మీ నైపుణ్యాలు, అనుభవం మరియు వృత్తిపరమైన ఆకాంక్షలను క్రింద వివరించండి మరియు మా AI అవకాశాలను ప్రకాశవంతం చేయనివ్వండి.",
    profile_placeholder: "ఉదా., 'రియాక్ట్ మరియు నోడ్.జెఎస్ లో 5 సంవత్సరాల అనుభవం, స్కేలబుల్ వెబ్ అప్లికేషన్‌లను నిర్మించడంలో ఆసక్తి. వేగవంతమైన స్టార్టప్‌లో సీనియర్ పాత్ర కోసం చూస్తున్నాను...'",
    location_placeholder: "ఉదా., ఇండియా",
    analyze_button: "నా మ్యాచ్ కనుగొనండి",
    analyzing: "మ్యాచ్‌లను కనుగొంటోంది...",
    error_title: "లోపం:",
    error_empty: "దయచేసి మీ ప్రొఫైల్‌ను వివరించండి మరియు ఒక స్థానాన్ని అందించండి.",
    error_generic: "ఊహించని లోపం సంభవించింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    loader_text: "మా AI మీ ఆదర్శ కెరీర్ మ్యాచ్‌ల కోసం శోధిస్తోంది...",
    match_results_title: "మీ కోసం కెరీర్ అవకాశాలు",
    summary_title: "ఇది ఎందుకు సరిపోలింది",
  },
  [Language.KN]: {
    app_title: "AI ವೃತ್ತಿ ಹೊಂದಾಣಿಕೆ",
    app_subtitle: "ನಿಮ್ಮ ಆದರ್ಶ ವೃತ್ತಿ ಮಾರ್ಗವನ್ನು ಅನ್ವೇಷಿಸಿ. ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳು, ಅನುಭವ, ಮತ್ತು ವೃತ್ತಿಪರ ಆಕಾಂಕ್ಷೆಗಳನ್ನು ಕೆಳಗೆ ವಿವರಿಸಿ, ಮತ್ತು ನಮ್ಮ AI ಸಾಧ್ಯತೆಗಳನ್ನು ಬೆಳಗಿಸಲಿ.",
    profile_placeholder: "ಉದಾ., 'ರಿಯಾಕ್ಟ್ ಮತ್ತು ನೋಡ್.ಜೆಎಸ್‌ನಲ್ಲಿ 5 ವರ್ಷಗಳ ಅನುಭವ, ಸ್ಕೇಲೆಬಲ್ ವೆಬ್ ಅಪ್ಲಿಕೇಶನ್‌ಗಳನ್ನು ನಿರ್ಮಿಸುವಲ್ಲಿ ಆಸಕ್ತಿ. ವೇಗದ ಗತಿಯ ಸ್ಟಾರ್ಟ್ಅಪ್‌ನಲ್ಲಿ ಹಿರಿಯ ಪಾತ್ರವನ್ನು ಹುಡುಕುತ್ತಿದ್ದೇನೆ...'",
    location_placeholder: "ಉದಾ., ಇಂಡಿಯಾ",
    analyze_button: "ನನ್ನ ಹೊಂದಾಣಿಕೆಯನ್ನು ಹುಡುಕಿ",
    analyzing: "ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    error_title: "ದೋಷ:",
    error_empty: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ವಿವರಿಸಿ ಮತ್ತು ಸ್ಥಳವನ್ನು ಒದಗಿಸಿ.",
    error_generic: "ಅನಿರೀಕ್ಷಿತ ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    loader_text: "ನಮ್ಮ AI ನಿಮ್ಮ ಆದರ್ಶ ವೃತ್ತಿ ಹೊಂದಾಣಿಕೆಗಳಿಗಾಗಿ ಹುಡುಕುತ್ತಿದೆ...",
    match_results_title: "ನಿಮಗಾಗಿ ವೃತ್ತಿ ಅವಕಾಶಗಳು",
    summary_title: "ಅದು ಏಕೆ ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತದೆ",
  },
  [Language.ML]: {
    app_title: "AI കരിയർ മാച്ച്",
    app_subtitle: "നിങ്ങളുടെ അനുയോജ്യമായ കരിയർ പാത കണ്ടെത്തുക. നിങ്ങളുടെ കഴിവുകൾ, അനുഭവം, പ്രൊഫഷണൽ അഭിലാഷങ്ങൾ എന്നിവ താഴെ വിവരിക്കുക, ഞങ്ങളുടെ AI സാധ്യതകളെ പ്രകാശിപ്പിക്കട്ടെ.",
    profile_placeholder: "ഉദാഹരണത്തിന്, 'റിയാക്റ്റിലും നോഡ്.ജെഎസിലും 5 വർഷത്തെ പരിചയം, സ്കെയിലബിൾ വെബ് ആപ്ലിക്കേഷനുകൾ നിർമ്മിക്കുന്നതിൽ താൽപ്പര്യം. അതിവേഗം വളരുന്ന ഒരു സ്റ്റാർട്ടപ്പിൽ ഒരു സീനിയർ റോളിനായി തിരയുന്നു...'",
    location_placeholder: "ഉദാഹരണത്തിന്, ഇന്ത്യ",
    analyze_button: "എന്റെ പൊരുത്തം കണ്ടെത്തുക",
    analyzing: "പൊരുത്തങ്ങൾ കണ്ടെത്തുന്നു...",
    error_title: "പിശക്:",
    error_empty: "ദയവായി നിങ്ങളുടെ പ്രൊഫൈൽ വിവരിക്കുകയും ഒരു സ്ഥലം നൽകുകയും ചെയ്യുക.",
    error_generic: "അപ്രതീക്ഷിതമായ പിശക് സംഭവിച്ചു. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    loader_text: "ഞങ്ങളുടെ AI നിങ്ങളുടെ അനുയോജ്യമായ കരിയർ പൊരുത്തങ്ങൾക്കായി തിരയുന്നു...",
    match_results_title: "നിങ്ങൾക്കുള്ള കരിയർ അവസരങ്ങൾ",
    summary_title: "എന്തുകൊണ്ടാണ് ഇത് പൊരുത്തപ്പെടുന്നത്",
  },
};

export const LANGUAGES = {
  [Language.EN]: "English",
  [Language.TA]: "தமிழ் (Tamil)",
  [Language.TE]: "తెలుగు (Telugu)",
  [Language.KN]: "ಕನ್ನಡ (Kannada)",
  [Language.ML]: "മലയാളം (Malayalam)",
};
